Add a notification setting to hide unread messages badges.
element-hq/element-x-ios pull request #2412
Opened 2024-02-01 12:33 UTC by pixlwave

Adds a setting that allows users to focus more by hiding grey unread dots on rooms that are set to only notify for mentions & keywords or not at all. Current strings are a placeholder, this PR isn't ready to merge until they've been added to Localazy.

https://github.com/element-hq/element-x-ios/assets/6060466/2f030ff2-ee05-4e70-901d-929c58805653

2024-02-01 12:33 UTC, pixlwave commented on ElementX/Resources/Localizations/en.lproj/Untranslated.strings
> +"screen_notification_settings_hide_unread_badges_description" = "Hide unread badges for rooms set to mute or mentions and keywords.";
Reminder to self: Waiting on real strings before this PR can be merged.

2024-02-01 12:39 UTC, amshakal commented
🥇 Sanity mode :'D

2024-02-02 09:01 UTC, Velin92 commented on ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
>                                hasUnreadMentions: details.unreadMentionsCount > 0,
I think you should handle this in the view and not here because the grey dot might also appear for a muted room, that has a mention and no unreads

2024-02-02 14:36 UTC, Velin92 commented on ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
>                                hasUnreadMentions: details.unreadMentionsCount > 0,
Or maybe is worth refactoring this HomeScreenRoom model so that it includes directly the logic that is used in the view to decide wether to display the dots, and in which color.

2024-02-02 14:48 UTC, Velin92 requested changes
Yeah would probably refactor HomeScreenRoom at this point to include the view logic directly

2024-02-05 18:29 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
>                                hasUnreadMentions: details.unreadMentionsCount > 0,
Makes sense to me, updated 👍

2024-02-06 11:49 UTC, Velin92 approved these changes

2024-02-07 12:24 UTC, pixlwave commented on ElementX/Resources/Localizations/en.lproj/Untranslated.strings
> +"screen_notification_settings_hide_unread_badges_description" = "Hide unread badges for rooms set to mute or mentions and keywords.";
The setting has been moved into Developer Options, and these strings have been removed.

2024-02-07 13:00 UTC, merged