Onboarding flow coordinator and FTUE changes
element-hq/element-x-ios pull request #2578
Opened 2024-03-15 13:12 UTC by stefanceriu

This PR introduces the following **significant** changes:
* session verification is mandatory for all users, the app shouldn't be usable without a verified session
* session verification / recovery, the (optional) app pin lock setup, the analytics consent prompt and the push notifications permissions requesting are now handled by the newly introduced OnboardingFlowCoordinator
* all traces of these flows have been removed from the AuthenticationFlowCoordinator and the main AppCoordinator, and consolidated in the Onboarding

Designs here https://www.figma.com/file/qjs3RKuofeKzBRPnOmLo2a/OIDC-sign-in-with-QR-code?type=design&node-id=19-144144&mode=design&t=7MXZzQhzq8C3h2uv-0

Known issues:
- [ ] designs not quite right yet
- [ ] a lot of snapshot tests are probably broken
- [ ] integrations tests need tweaking

2024-03-19 12:35 UTC, pixlwave requested changes
Wooo, finally an onboarding flow 👏

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Resources/Assets.xcassets/images/Alerts.imageset/Contents.json
Should be lower cased `alerts` and also, maybe we should call this `notifications-prompt-graphic` or similar so it's obvious which feature it belongs to?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
> +    }
Hold on, can't we store this in user defaults like we do for `shouldShowAnalyticsPrompt`? Then it doesn't need to be async, and if someone doesn't want notifications, we won't keep aggressively showing them the prompt over and over.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Services/Notification/Manager/NotificationManager.swift
> +        await notificationCenter.authorizationStatus() == .notDetermined
The name of this method doesn't line up with its contents to my eyes?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
> +        await configureStateMachine()
Then if the notifications is in user defaults, this configuration could go into the init too.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +
This is too late for the AppLock step (and I would say the same for analytics and probably notifications too). When app lock is mandatory, the user shouldn't be able to do anything in the app until they've set a PIN.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/HeroImage.swift
> +                return .compound.iconSecondaryAlpha
I think we need to ask Design about this. We just moved away from that (I think it was meant for the October release but we were late on iOS) and now we're switching back to it again?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/HeroImage.swift
> +    enum Style {
👌

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
> +            if context.viewState.securityBannerMode == .recoveryKeyConfirmation {
I'm not sure I follow this (I always get confused with verification/recovery/backup). We want to require verification, which *should* get the recovery key set up. But if it's missing, then it's fine to use the app even though you might not have access to all of your messages? Is that what we want?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +            MXLog.error("Sir, This Is A Wendy's")
😂

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
> +                UIApplication.shared.open("https://element.io/help#encryption")
Can we pass this in from `AppSettings` like we do with the copyright/privacy/acceptable use URLs?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
> +                    .padding(.top, 16)
That should probably go on the button rather than the label.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
> +                    .foregroundColor(.compound.textPrimary)
This should be `textActionPrimary`, although a better alternative would be to use the plain style from compound and then you wouldn't need the `Text`.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmedScreen/View/IdentityConfirmedScreen.swift
> +                .foregroundColor(.compound.textSecondary)
We should be using fonts from Compound here.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
> +                .foregroundColor(.compound.textSecondary)
And the same here.

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/NotificationPermissionsScreenCoordinator.swift
> +    var actions: AnyPublisher<NotificationPermissionsScreenCoordinatorAction, Never> {
`actionsPublisher` perhaps now?

2024-03-19 12:35 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/View/NotificationPermissionsScreen.swift
> +                    .font(.compound.bodyLGSemibold)
Don't think you need this with the button style, can just be a string in the init.

2024-03-19 13:21 UTC, stefanceriu commented on ElementX/Sources/Other/SwiftUI/Layout/FullscreenDialog.swift
> -                .background()
Oh interesting, but it's hiding the bottom fade 🤔

2024-03-19 13:23 UTC, stefanceriu commented on ElementX/Resources/Assets.xcassets/images/background-bottom-light.imageset/Contents.json
Oh, I'm a dummy, I though there's no dark variants, completely missed it in this list https://www.figma.com/file/ux3tYoZV9WghC7hHT9Fhk0/Compound-iOS-Components?type=design&node-id=1642-19118&mode=design&t=TkhuugFozbikoh0o-0

2024-03-19 13:25 UTC, stefanceriu commented on ElementX/Sources/Other/SwiftUI/Views/HeroImage.swift
> +                return .compound.iconSecondaryAlpha
I'm just going off the new(!?) designs for login with qr? https://www.figma.com/file/qjs3RKuofeKzBRPnOmLo2a/OIDC-sign-in-with-QR-code?type=design&node-id=1-839&mode=design&t=JNPzlFbWQpQpFGED-0

2024-03-19 15:27 UTC, stefanceriu commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
> +            if context.viewState.securityBannerMode == .recoveryKeyConfirmation {
This bit is only about your current recovery setup going out of sync with what happens on other devices. If for example you reset your backup from somewhere else then this banner will pop in and let you sync it back up

2024-03-19 15:36 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmedScreen/View/IdentityConfirmedScreen.swift
> +                .foregroundColor(.compound.textSecondary)
Ha, I think I copied these from the SessionVerificationScreen. I'll update all of them 👍

2024-03-19 15:46 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/View/NotificationPermissionsScreen.swift
> +                    .font(.compound.bodyLGSemibold)
Copied it from the `AnalyticsPromptScreen` 🙈

2024-03-19 15:50 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/NotificationPermissionsScreenCoordinator.swift
> +    var actions: AnyPublisher<NotificationPermissionsScreenCoordinatorAction, Never> {
We should go rename all of them at some point

2024-03-20 17:12 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/View/NotificationPermissionsScreen.swift
> -        .background()
Same here.

2024-03-20 17:16 UTC, pixlwave commented on PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-en-GB.1.png
These look sooo good now 🤩

2024-03-20 17:59 UTC, stefanceriu commented
> although I think you're missing the commit with the changes you were showing me to the flow

Oh that's mega weird, the push failed and I didn't notice 🤔 It's up now.

2024-03-20 18:02 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/AnalyticsPromptScreen/View/AnalyticsPromptScreen.swift
> -        .background()
Oh right, now I understand how it all links together 👍

2024-03-20 18:04 UTC, stefanceriu commented on PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-en-GB.1.png
🕺

2024-03-21 10:00 UTC, pixlwave approved these changes
LGTM 🚀

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
> +        guard stateMachine.state == .initial, !ProcessInfo.isRunningIntegrationTests else {
Definitely for a follow-up PR, but we should create a UI test (or multiple) for this flow to make sure we have the expected paths covered.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
> +        !appSettings.hasRunIdentityConfirmationOnboarding || userSession.sessionSecurityStatePublisher.value.verificationState == .unverified
It might be good to add a comment somewhere about why we're doing it like this.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
> +        let requiresNotificationsSetup = requiresNotificationsSetup
Think this could go directly in the switch now?

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +        }
Don't think we need the else now right? As its reset on signout.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +        if !isNewLogin {
From my looking, it wouldn't do anything bad if we didn't have that `!isNewLogin` here right? Otherwise there's the super super edge case of 
- sign in
- verify
- reset verification from another client before relaunching the app.

Which goes unhandled.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +                self?.updateWithSessionSecurityState(state)
Honestly, I'm less keen on this pattern where you can't see at the call site that something is actually async.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +    private static let loadingIndicatorIdentifier = "AppCoordinatorLoading"
*cough* AppCoordinator *cough*

Side note: Maybe we should get into the habit of using something like `"\(Self.self)-Loading"`.

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/Screens/RoomScreen/View/Timeline/EncryptedHistoryRoomTimelineView.swift
👏

2024-03-21 10:00 UTC, pixlwave commented on ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
> +        // Otherwise check if we need to add anything to the top of the timeline.
```suggestion
        // Check if we need to add anything to the top of the timeline.
```

2024-03-21 11:08 UTC, stefanceriu commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +        }
Good catcht, thanks 👍

2024-03-21 11:09 UTC, stefanceriu commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +        if !isNewLogin {
Fair, definitely safer to always check 👍

2024-03-21 11:19 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +    private static let loadingIndicatorIdentifier = "AppCoordinatorLoading"
Unfortunately Self isn't available at that time but I can do `"\(IdentityConfirmationScreenViewModel.self)-Loading"`

2024-03-21 11:24 UTC, pixlwave commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +    private static let loadingIndicatorIdentifier = "AppCoordinatorLoading"
Ah, boooo. May as well just be a plain string at that point, using a hard coded class name doesn't exactly have any advantage over `"IdentityConfirmationLoading"`

2024-03-21 11:38 UTC, stefanceriu commented on ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
> +    private static let loadingIndicatorIdentifier = "AppCoordinatorLoading"
The advantage is that you can rename the class without having to worry about it, so I think it's still worth it.

2024-03-21 12:01 UTC, merged