Support for posthog super properties
element-hq/element-x-ios pull request #2579
Opened 2024-03-15 15:38 UTC by BillCarsonFr

### Pull Request Checklist

A quick PR to add super properties to captured event. Super properties are added to every captured event.
In this case I added on super property for `cryptoSDK`, we used this property as a filter on `$screen` events (as well as E2E errors). It allows to build a ratio of errors for all different clients just using this filter.

Let me know if ok

- [ ] I read the [contributing guide](https://github.com/element-hq/element-ios/blob/develop/CONTRIBUTING.md)
- [ ] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [ ] iPhone and iPad simulators in portrait and landscape orientations.
- [ ] Dark mode enabled and disabled.
- [ ] Various sizes of dynamic type.
- [ ] Voiceover enabled.

2024-03-15 15:52 UTC, stefanceriu requested changes

2024-03-15 15:52 UTC, stefanceriu commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +    private var superProperties: [String: Any] = [:]
Why don't we define and type these similar to [AnalyticsEvent.UserProperties](https://github.com/matrix-org/matrix-analytics-events/blob/main/schemas/UserProperties.json)?

2024-03-15 15:52 UTC, stefanceriu commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        superProperties["cryptoSDK"] = "Rust"
.. would make this less.. stringy

2024-03-15 15:52 UTC, stefanceriu commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        postHog?.screen(event.screenName.rawValue, properties: attachUserProperties(to: attachSuperProperties(to: event.properties)))
This is not the most straightforward thing, some tests are in order. Please see `UnitTests/AnalyticsTests`, especiall the `*UserProperties` part

2024-03-19 12:47 UTC, pixlwave commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        superProperties["cryptoSDK"] = "Rust"
Agreed, we shouldn't be sending anything to PostHog that isn't coming from the schema.

2024-03-21 13:26 UTC, BillCarsonFr commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        superProperties["cryptoSDK"] = "Rust"
We can't define that in the schema (properties added to build in events)

2024-03-21 13:27 UTC, BillCarsonFr commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +    private var superProperties: [String: Any] = [:]
We need this property in Screen events to have common filters for each platforms. Screen events are built in, and not defined in the analytics repo

2024-03-21 13:28 UTC, BillCarsonFr commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +    private var superProperties: [String: Any] = [:]
Oh I see, just define a blank object in the repo

2024-03-21 14:01 UTC, pixlwave commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        superProperties["cryptoSDK"] = "Rust"
It should be possible to make a `SuperProperties` event and attach it's `.properties` to the event's that we're sending instead of an untyped dictionary though?

2024-03-26 09:38 UTC, BillCarsonFr commented on ElementX/Sources/Services/Analytics/PostHogAnalyticsClient.swift
> +        superProperties["cryptoSDK"] = "Rust"
https://github.com/matrix-org/matrix-analytics-events/pull/95

2024-04-22 15:10 UTC, stefanceriu commented
@BillCarsonFr planning on coming back to this PR at some point or can we close it?

2024-05-02 10:48 UTC, BillCarsonFr commented
Closing in favour of https://github.com/element-hq/element-x-ios/pull/2774

2024-05-02 10:48 UTC, closed without merging