Automatically try reloading failed images on network changes
element-hq/element-x-ios pull request #3168
Opened 2024-08-14 14:19 UTC by stefanceriu

Fixes #3110

This PR passes over the network monitor to the LoadableImage so that it can be used together with the already passed ImageLoader to automatically reload images when network conditions change.

2024-08-14 15:17 UTC, pixlwave approved these changes

2024-08-14 15:17 UTC, pixlwave commented on UITests/Sources/__Snapshots__/Application/roomRolesAndPermissionsFlow-1-iPad-10th-generation-en-GB.UI.png
We should really fix this and make the mock media provider return the same image on both paths 🫠

2024-08-14 15:17 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
My 1 constructive comment: Would it be worth only setting up the subscription if the loading fails?

2024-08-14 16:01 UTC, Velin92 requested changes
Before merging this I wanted to give another possible solution which I feel may be easier and more scalable for this refactor, here is my take in our internal room:

https://matrix.to/#/!JTahvxBRtQfZViMwKT:matrix.org/$ZPQcvASHkqaIFhXNRnK0ETios37A9FVsUpFMg5gvCD8?via=matrix.org&via=element.io

I'll be on holidays until next week, so feel free to disregard this suggestion if you feel is not worth it.

2024-08-15 12:10 UTC, stefanceriu commented
> I wanted to give another possible solution which I feel may be easier and more scalable for this refactor

Thanks for that! We ended up building something similar but based on plain tasks instead of publishers in #3170

2024-08-15 12:10 UTC, closed without merging