Knocked Preview implementation
element-hq/element-x-ios pull request #3426
Opened 2024-10-18 11:22 UTC by Velin92

2024-10-22 16:50 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendImage(url: url.path(percentEncoded: false), thumbnailUrl: thumbnailURL.path(percentEncoded: false), imageInfo: imageInfo, caption: nil, formattedCaption: nil, storeI
this is related to the latest SDK update, for now I have set it to false, there are other instances where I did the same, but I am unsure if this is the expected value

2024-10-22 16:50 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendVideo(url: url.path(percentEncoded: false), thumbnailUrl: thumbnailURL.path(percentEncoded: false), videoInfo: videoInfo, caption: nil, formattedCaption: nil, storeI
as the comment above

2024-10-22 16:50 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendVoiceMessage(url: url.path(percentEncoded: false), audioInfo: audioInfo, waveform: waveform, caption: nil, formattedCaption: nil, storeInCache: false, progressWatche
as the comment above

2024-10-22 16:50 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendAudio(url: url.path(percentEncoded: false), audioInfo: audioInfo, caption: nil, formattedCaption: nil, storeInCache: false, progressWatcher: UploadProgressListener {
as the comment above

2024-10-22 16:51 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendFile(url: url.path(percentEncoded: false), fileInfo: fileInfo, storeInCache: false, progressWatcher: UploadProgressListener { progress in
as the comment above

2024-10-23 06:44 UTC, stefanceriu commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendImage(url: url.path(percentEncoded: false), thumbnailUrl: thumbnailURL.path(percentEncoded: false), imageInfo: imageInfo, caption: nil, formattedCaption: nil, storeI
I raised [a separate PR](https://github.com/element-hq/element-x-ios/pull/3437) for adopting these (based on my existing branch). Let's get that merged and then rebase this PR on top of it.

2024-10-23 07:49 UTC, stefanceriu requested changes

2024-10-23 07:58 UTC, Velin92 commented on ElementX/Resources/Localizations/en.lproj/Localizable.strings
> +"screen_knocked_knock_sent" = "Request to join sent";
reusing the same for the invite which id `screen_invited_invite`, but yeah can change it

2024-10-23 08:00 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
> +        default: nil
the thing is that a room may also be left, joined or simply not joined at all, this property jst tells you that there is currently a join request pending, and if is an invite or a knock

2024-10-23 08:02 UTC, Velin92 commented on ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
> +        FullscreenDialog(topPadding: context.viewState.mode == .knocked ? 151 : 35, background: .bloom) {
just following the figma redesign values 🤷‍♂️

2024-10-23 08:14 UTC, stefanceriu commented on ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
> +        default: nil
Okay, fair 👍

2024-10-23 08:16 UTC, stefanceriu commented on ElementX/Resources/Localizations/en.lproj/Localizable.strings
> +"screen_knocked_knock_sent" = "Request to join sent";
Wait, I'm confused now, there's no `screen_invited` in localazy 🤔 

Either way, if they're in the join screen it should be prefixed with `screen_join_room`

2024-10-23 08:17 UTC, stefanceriu commented on ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
> +        FullscreenDialog(topPadding: context.viewState.mode == .knocked ? 151 : 35, background: .bloom) {
Strange but okay ¯\_(ツ)_/¯

2024-10-23 10:26 UTC, Velin92 commented on ElementX/Resources/Localizations/en.lproj/Localizable.strings
> +"screen_knocked_knock_sent" = "Request to join sent";
sorry it wasn't screen_invited but: `screen_invites_invited_you`
Also this is not related to the join_room but the home screen cell, is essentially the copy displayed in this new cell that will appear for knocked rooms in the room list

2024-10-23 10:30 UTC, Velin92 commented on ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
> +                RoomHeaderView(roomName: context.viewState.title,
Well is only reused here, and only for one specific mode. Doesn't sound too bad to reuse it here. But maybe to make things easier I could make a modifier for it. The problem is that the RoomScreen one contains way more accessories, that we don't need here

2024-10-23 10:31 UTC, Velin92 commented on ElementX/Sources/Services/Timeline/TimelineProxy.swift
> +        let handle = timeline.sendImage(url: url.path(percentEncoded: false), thumbnailUrl: thumbnailURL.path(percentEncoded: false), imageInfo: imageInfo, caption: nil, formattedCaption: nil, storeI
done!

2024-10-23 10:32 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
> +        default: nil
Actually let me improve this a bit more, I feel the `.invite` case should also have an optional `inviter` associated value

2024-10-23 11:41 UTC, stefanceriu approved these changes
Very nice! 👏

2024-10-24 15:23 UTC, merged