Update sdk to 1.0.78
element-hq/element-x-ios pull request #3586
Opened 2024-12-04 16:40 UTC by Velin92

2024-12-04 16:41 UTC, Velin92 commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +                    analytics.trackError(context: nil, domain: .E2EE, name: .UnknownError, timeToDecryptMillis: timeToDecryptMs)
@stefanceriu @pixlwave there seems to be there is no specific case for this one, or should we use the `.RoomKeysWithheldForUnverifiedDevice` also here?

2024-12-04 17:05 UTC, pixlwave approved these changes
LGTM 👍

2024-12-04 17:05 UTC, pixlwave commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +                    analytics.trackError(context: nil, domain: .E2EE, name: .UnknownError, timeToDecryptMillis: timeToDecryptMs)
Certainly sounds reasonable to me, might be worth checking with the crypto team to confirm?

2024-12-04 17:08 UTC, Velin92 commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +                    analytics.trackError(context: nil, domain: .E2EE, name: .UnknownError, timeToDecryptMillis: timeToDecryptMs)
@BillCarsonFr tagging you to be sure if I should use` .RoomKeysWithheldForUnverifiedDevice` for both these cases

2024-12-05 09:40 UTC, BillCarsonFr requested changes
I clarified what string/code to use for withheldBySender

2024-12-05 09:40 UTC, BillCarsonFr commented on ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
> +                    analytics.trackError(context: nil, domain: .E2EE, name: .UnknownError, timeToDecryptMillis: timeToDecryptMs)
For `.withheldBySender` use `OlmKeysNotSentError`

2024-12-05 09:40 UTC, BillCarsonFr commented on ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
> +                errorLabel = L10n.timelineDecryptionFailureWithheldUnverified
No here for `withheldBySender` you can use the localazy key `timeline.decryption_failure.unable_to_decrypt`

2024-12-05 09:55 UTC, merged